<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261009161444 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE heating_start (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, setpoint NUMERIC(3, 1) NOT NULL, indoor_temperature NUMERIC(4, 1) NOT NULL, place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_heating_start_place_started_at ON heating_start (place_id, started_at)');
        $this->addSql('CREATE INDEX IDX_5ABED71EDA6A219 ON heating_start (place_id)');
        $this->addSql('ALTER TABLE heating_start ADD CONSTRAINT FK_5ABED71EDA6A219 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE heating_start DROP CONSTRAINT FK_5ABED71EDA6A219');
        $this->addSql('DROP TABLE heating_start');
    }
}
