<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261009075959 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE heating_target (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slot VARCHAR(16) NOT NULL, temperature NUMERIC(3, 1) NOT NULL, household_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_heating_target_household_slot ON heating_target (household_id, slot)');
        $this->addSql('CREATE INDEX IDX_C1A24BACE79FF843 ON heating_target (household_id)');
        $this->addSql('CREATE TABLE household (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(120) DEFAULT NULL, latitude NUMERIC(8, 5) DEFAULT NULL, longitude NUMERIC(8, 5) DEFAULT NULL, timezone VARCHAR(64) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_54C32FC0A76ED395 ON household (user_id)');
        $this->addSql('CREATE TABLE place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, household_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_place_household_name ON place (household_id, name)');
        $this->addSql('CREATE INDEX IDX_741D53CDE79FF843 ON place (household_id)');
        $this->addSql('CREATE TABLE reading (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, measured_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, outdoor_temperature NUMERIC(4, 1) NOT NULL, indoor_temperature NUMERIC(4, 1) NOT NULL, place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_reading_place_measured_at ON reading (place_id, measured_at)');
        $this->addSql('CREATE INDEX IDX_C11AFC41DA6A219 ON reading (place_id)');
        $this->addSql('ALTER TABLE heating_target ADD CONSTRAINT FK_C1A24BACE79FF843 FOREIGN KEY (household_id) REFERENCES household (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE household ADD CONSTRAINT FK_54C32FC0A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE place ADD CONSTRAINT FK_741D53CDE79FF843 FOREIGN KEY (household_id) REFERENCES household (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reading ADD CONSTRAINT FK_C11AFC41DA6A219 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE heating_target DROP CONSTRAINT FK_C1A24BACE79FF843');
        $this->addSql('ALTER TABLE household DROP CONSTRAINT FK_54C32FC0A76ED395');
        $this->addSql('ALTER TABLE place DROP CONSTRAINT FK_741D53CDE79FF843');
        $this->addSql('ALTER TABLE reading DROP CONSTRAINT FK_C11AFC41DA6A219');
        $this->addSql('DROP TABLE heating_target');
        $this->addSql('DROP TABLE household');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE reading');
    }
}
