<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261009110248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE place_target (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slot VARCHAR(16) NOT NULL, temperature NUMERIC(3, 1) NOT NULL, place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_place_target_place_slot ON place_target (place_id, slot)');
        $this->addSql('CREATE INDEX IDX_E4A12895DA6A219 ON place_target (place_id)');
        $this->addSql('ALTER TABLE place_target ADD CONSTRAINT FK_E4A12895DA6A219 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE place_target DROP CONSTRAINT FK_E4A12895DA6A219');
        $this->addSql('DROP TABLE place_target');
    }
}
